# Data Manipulation with NumPy
NumPy (Numerical Python) is a powerful, open-source library in Python that is fundamental for scientific computing. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to perform operations on these arrays. NumPy is the foundational package for many other data science and machine learning libraries in Python, such as pandas, SciPy, and scikit-learn.

## Introduction to NumPy arrays
NumPy is a fundamental package for scientific computing in Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays. This tutorial introduces NumPy arrays, covering their creation, properties, and basic operations. By the end of this tutorial, you'll have a solid understanding of how to manipulate data efficiently using NumPy arrays.
### Installing NumPy
To use NumPy, you first need to install it. You can do this using pip:


In [ ]:
pip install numpy

### Importing NumPy
Before you can start using NumPy, you need to import it into your Python environment:


In [ ]:
import numpy as np

### Creating NumPy Arrays
NumPy arrays can be created from lists or tuples using the np.array function.

#### From a list:


In [ ]:
import numpy as np

# Creating a 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

# Creating a 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)


#### Using built-in functions:
NumPy provides several functions to create arrays quickly.
-   np.zeros: Creates an array of zeros
-   np.ones: Creates an array of ones
-   np.arange: Creates an array with a range of values
-   np.linspace: Creates an array with evenly spaced values between a specified interval


In [ ]:
# Array of zeros
zeros = np.zeros((2, 3))
print(zeros)

# Array of ones
ones = np.ones((2, 3))
print(ones)

# Array with a range of values
range_arr = np.arange(0, 10, 2)
print(range_arr)

# Array with evenly spaced values
linspace_arr = np.linspace(0, 1, 5)
print(linspace_arr)


### Array Attributes
NumPy arrays have several important attributes:
-   shape: The dimensions of the array
-   dtype: The data type of the elements
-   size: The number of elements in the array
-   ndim: The number of dimensions (axes) of the array


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Shape:", arr.shape)
print("Data type:", arr.dtype)
print("Size:", arr.size)
print("Number of dimensions:", arr.ndim)


### Array Indexing and Slicing
NumPy arrays can be indexed and sliced in a manner similar to Python lists but with more powerful capabilities for multi-dimensional arrays.


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Accessing elements
print(arr[0, 1])  # Output: 2

# Slicing arrays
print(arr[0, :])  # Output: [1 2 3]
print(arr[:, 1])  # Output: [2 5]


### Array Operations
NumPy allows you to perform element-wise operations on arrays as well as matrix operations.
Element-wise operations:


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Addition
print(arr1 + arr2)

# Subtraction
print(arr1 - arr2)

# Multiplication
print(arr1 * arr2)

# Division
print(arr1 / arr2)


### Matrix operations:

In [ ]:
arr3 = np.array([[1, 2], [3, 4]])
arr4 = np.array([[5, 6], [7, 8]])

# Dot product
print(np.dot(arr3, arr4))

# Transpose
print(arr3.T)


## Basic array operations
NumPy is a powerful library for numerical computing in Python. It provides support for multi-dimensional arrays and a wide range of operations to manipulate them. In this tutorial, we will focus strictly on basic array operations including arithmetic operations, statistical functions, array manipulation, and universal functions.

### Arithmetic Operations
NumPy allows you to perform element-wise arithmetic operations on arrays.
Basic Operations:


In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Addition
print(arr1 + arr2)  # Output: [5 7 9]

# Subtraction
print(arr1 - arr2)  # Output: [-3 -3 -3]

# Multiplication
print(arr1 * arr2)  # Output: [ 4 10 18]

# Division
print(arr1 / arr2)  # Output: [0.25 0.4  0.5 ]


### Scalar Operations:

In [ ]:
# Add a scalar to an array
print(arr1 + 10)  # Output: [11 12 13]

# Multiply an array by a scalar
print(arr1 * 3)   # Output: [3 6 9]


### Statistical Functions:
NumPy provides functions to perform common statistical operations on arrays.


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Sum of all elements
print(np.sum(arr))  # Output: 21

# Mean of all elements
print(np.mean(arr))  # Output: 3.5

# Standard deviation of all elements
print(np.std(arr))  # Output: 1.707825127659933

# Maximum and minimum values
print(np.max(arr))  # Output: 6
print(np.min(arr))  # Output: 1

# Sum along an axis (0 for columns, 1 for rows)
print(np.sum(arr, axis=0))  # Output: [5 7 9]
print(np.sum(arr, axis=1))  # Output: [ 6 15]


### Array Manipulation
NumPy provides functions for reshaping, stacking, and splitting arrays.
Reshaping Arrays:


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Reshape to a different shape
reshaped_arr = arr.reshape((3, 2))
print(reshaped_arr)


### Stacking Arrays:

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Vertical stack
vstack_arr = np.vstack((arr1, arr2))
print(vstack_arr)  # Output: [[1 2 3]
                  #          [4 5 6]]

# Horizontal stack
hstack_arr = np.hstack((arr1, arr2))
print(hstack_arr)  # Output: [1 2 3 4 5 6]


### Splitting Arrays:

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Split array into two equal parts
split_arr = np.hsplit(arr, 2)
print(split_arr)  # Output: [array([[1, 2],
                  #                 [4, 5]]), array([[3],
                  #                                  [6]])]

# Vertical split
split_arr = np.vsplit(arr, 2)
print(split_arr)  # Output: [array([[1, 2, 3]]), array([[4, 5, 6]])]


## Universal Functions (ufuncs)
Universal functions (ufuncs) operate element-wise on arrays and provide a range of mathematical operations.
Examples of ufuncs:


In [ ]:
arr = np.array([1, 2, 3, 4, 5])

# Square root
sqrt_arr = np.sqrt(arr)
print(sqrt_arr)  # Output: [1.         1.41421356 1.73205081 2.         2.23606798]

# Exponential
exp_arr = np.exp(arr)
print(exp_arr)  # Output: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]

# Sine
sin_arr = np.sin(arr)
print(sin_arr)  # Output: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


### Boolean Indexing and Filtering
Boolean indexing allows you to filter elements in an array based on conditions.


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])

# Filter elements greater than 3
filtered_arr = arr[arr > 3]
print(filtered_arr)  # Output: [4 5 6]

# Filter using multiple conditions
filtered_arr = arr[(arr > 2) & (arr < 5)]
print(filtered_arr)  # Output: [3 4]


### Indexing and slicing
NumPy provides powerful tools for indexing and slicing arrays, allowing for efficient access and manipulation of array elements. This tutorial will focus strictly on these operations, showing how to extract, modify, and manipulate subarrays in NumPy.
#### Indexing
Indexing in NumPy arrays works similarly to standard Python lists but extends to multi-dimensional arrays.
##### 1D Arrays:


In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

# Accessing individual elements
print(arr[0])  # Output: 10
print(arr[2])  # Output: 30
print(arr[-1]) # Output: 50


##### 2D Arrays:

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Accessing individual elements
print(arr[0, 0])  # Output: 1
print(arr[1, 2])  # Output: 6
print(arr[-1, -1]) # Output: 9


#### Slicing
Slicing allows you to extract subarrays from your NumPy arrays. The syntax for slicing is start:stop:step.

##### 1D Arrays:


In [ ]:
arr = np.array([10, 20, 30, 40, 50])

# Slicing elements
print(arr[1:4])    # Output: [20 30 40]
print(arr[:3])     # Output: [10 20 30]
print(arr[::2])    # Output: [10 30 50]
print(arr[::-1])   # Output: [50 40 30 20 10]


##### 2D Arrays:

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Slicing rows and columns
print(arr[1:, :2])   # Output: [[4 5]
                    #          [7 8]]

print(arr[:2, 1:])   # Output: [[2 3]
                    #          [5 6]]

print(arr[:, ::2])   # Output: [[1 3]
                    #          [4 6]
                    #          [7 9]]


### Slicing with Negative Indices:

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Using negative indices in slicing
print(arr[-2:, -2:])  # Output: [[5 6]
                      #          [8 9]]

print(arr[:-1, :-1])  # Output: [[1 2]
                      #          [4 5]]


## Advanced Indexing
### Boolean Indexing:


In [ ]:
arr = np.array([10, 20, 30, 40, 50])

# Boolean indexing
mask = arr > 25
print(arr[mask])  # Output: [30 40 50]

arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
mask2d = arr2d > 4
print(arr2d[mask2d])  # Output: [5 6 7 8 9]


### Fancy Indexing:

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

# Fancy indexing with a list of indices
print(arr[[0, 2, 4]])  # Output: [10 30 50]

arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d[[0, 1, 2], [2, 1, 0]])  # Output: [3 5 7]


### Modifying Array Elements
#### Assigning Values to Slices:


In [ ]:
arr = np.array([10, 20, 30, 40, 50])

# Modifying elements through slicing
arr[1:4] = [200, 300, 400]
print(arr)  # Output: [ 10 200 300 400  50]

arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[:2, 1:] = [[20, 30], [50, 60]]
print(arr2d)  # Output: [[ 1 20 30]
              #          [ 4 50 60]
              #          [ 7  8  9]]


#### Using Boolean Indexing to Modify Elements:

In [ ]:
arr = np.array([10, 20, 30, 40, 50])

# Modifying elements using boolean indexing
arr[arr > 25] = 100
print(arr)  # Output: [ 10  20 100 100 100]

arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[arr2d % 2 == 0] = 0
print(arr2d)  # Output: [[1 0 3]
              #          [0 5 0]
              #          [7 0 9]]


## Broadcasting
Broadcasting is a powerful feature in NumPy that allows arithmetic operations on arrays of different shapes. It makes it possible to perform element-wise operations without the need to manually reshape arrays. This tutorial will focus strictly on broadcasting, explaining the rules and providing examples to illustrate its usage.
### Rules of Broadcasting
If the arrays do not have the same rank, prepend the shape of the lower-rank array with ones until both shapes have the same length.
The sizes of the arrays must match or one of them must be 1 in all dimensions.
### Examples of Broadcasting
#### Example 1: Adding a Scalar to an Array
In this example, the scalar 5 is broadcasted to match the shape of the array arr.


In [ ]:
import numpy as np

arr = np.array([1, 2, 3])
scalar = 5

# Adding a scalar to an array
result = arr + scalar
print(result)  # Output: [6 7 8]


#### Example 2: Adding Arrays of Different Shapes
Here, arr1 has shape (3,) and arr2 has shape (3, 1). During broadcasting, arr1 is reshaped to (1, 3) and then stretched to (3, 3).


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([[10], [20], [30]])

# Adding arrays of different shapes
result = arr1 + arr2
print(result)
# Output:
# [[11 12 13]
#  [21 22 23]
#  [31 32 33]]


#### Example 3: Subtracting Arrays with One Dimension of Size 1
In this case, arr2 is broadcasted to match the shape of arr1, resulting in an element-wise subtraction.


In [ ]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([10, 20, 30])

# Subtracting arrays
result = arr1 - arr2
print(result)
# Output:
# [[-9 -18 -27]
#  [-6 -15 -24]]


### Practical Use Cases
Normalizing Data:
Here, the mean of each column is subtracted from the corresponding column elements in data.


In [ ]:
data = np.array([[1, 2], [3, 4], [5, 6]])
mean = np.mean(data, axis=0)

# Broadcasting mean to normalize data
normalized_data = data - mean
print(normalized_data)
# Output:
# [[-2. -2.]
#  [ 0.  0.]
#  [ 2.  2.]]


#### Scaling Data:
In this example, each column of data is scaled by the corresponding element in scales.


In [ ]:
data = np.array([[1, 2], [3, 4], [5, 6]])
scales = np.array([0.1, 0.2])

# Broadcasting scales to multiply data
scaled_data = data * scales
print(scaled_data)
# Output:
# [[0.1 0.4]
#  [0.3 0.8]
#  [0.5 1.2]]


### Broadcasting with Multi-dimensional Arrays
#### Example: Element-wise Operations on Higher-dimensional Arrays
In this example, arr1 has shape (2, 3, 1) and arr2 has shape (3,). During broadcasting, arr2 is reshaped to (1, 3) and then broadcasted to (2, 3, 3).


In [ ]:
arr1 = np.array([[[1], [2], [3]], [[4], [5], [6]]])
arr2 = np.array([10, 20, 30])

# Adding arrays with different shapes
result = arr1 + arr2
print(result)
# Output:
# [[[11 21 31]
#   [12 22 32]
#   [13 23 33]]
# 
#  [[14 24 34]
#   [15 25 35]
#   [16 26 36]]]
